### ISSUE TITLE
VectorCloud not working

### ISSUE THREAD

**Issue by Jasonthefirst** [rmountjoy92/VectorCloud#15]
I tried starting Vector Cloud on multiple systems with different OSs. 
It runs but as soon as I try to open the page on localhost:5000 the page throws a error: "file not found". 
And python throws: 

```
` * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Jan/2019 11:52:59] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\*******\VectorCloud\venv\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\*******\VectorCloud\venv\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\*******\VectorCloud\venv\lib\site-packages\flask_restful\__init__.py", line 269, in error_router
    return original_handler(e)
  File "C:\Users\*******\VectorCloud\venv\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\*******\VectorCloud\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\*******\VectorCloud\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\*******\VectorCloud\venv\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\*******\VectorCloud\venv\lib\site-packages\flask\app.py", line 1833, in finalize_request
    response = self.process_response(response)
  File "C:\Users\*******\VectorCloud\venv\lib\site-packages\flask\app.py", line 2112, in process_response
    response = handler(response)
  File "C:\Users\*******\VectorCloud\vectorcloud\main\routes.py", line 62, in add_header
    clear_temp_folder()
  File "C:\Users\*******\VectorCloud\vectorcloud\application_store\utils.py", line 22, in clear_temp_folder
    file_list = os.listdir(temp_folder)
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\Users\\demia\\Documents\\Programing\\Privat\\VectorCloud\\vectorcloud\\application_store\\temp'
127.0.0.1 - - [28/Jan/2019 11:52:59] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [28/Jan/2019 11:53:00] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [28/Jan/2019 11:53:00] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [28/Jan/2019 11:53:00] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [28/Jan/2019 11:53:00] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

Process finished with exit code -1
`
```

I used python 3.6, 3.7 and 3.72 with an virtual env or directly. I tried this with Raspbian, Ubuntu in WSL, Docker and Python on Windows. 
Any hints or is this currently a bug or am I doing something wrong?

Thanks a lot. 
Dede

**Comment by rmountjoy92** [comment]
Grr stupid temp folder issue again. I will fix today when I get home for work, for now create the following directory: VectorCloud/vectorcloud/application_store/temp/

That should fix it.

**Comment by rmountjoy92** [comment]
I just pushed the fix, it should now create the temp folder when you execute run.py. Let me know if that got it working!

**Comment by Jasonthefirst** [comment]
Wow. That was quick. I am positively baffled. Thanks a lot. The fix worked and the page opened. 
I will play with vector and VectorCloud later and try everything. Thank you very much.
