### ISSUE TITLE
'>' not supported between instances of 'NoneType' and 'float'

### ISSUE THREAD

**Issue by Jasonthefirst** [rmountjoy92/VectorCloud#16]
I tried to play with vectorcloud but now got stuck after choosing a username and password. The page searches for vector, appears to find him: 

> anki_vector.connection.Connection INFO     Connecting to 192.168.*.***:443 for Vector-****using C:\Users\*******\.anki_vector\Vector-****-********.cert

but then crashes with: 

`127.0.0.1 - - [29/Jan/2019 20:23:17] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\*****\VectorCloud\venv\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\*****\VectorCloud\venv\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\*****\VectorCloud\venv\lib\site-packages\flask_restful\__init__.py", line 269, in error_router
    return original_handler(e)
  File "C:\Users\*****\VectorCloud\venv\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\*****\VectorCloud\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\*****\VectorCloud\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\*****\VectorCloud\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\*****\VectorCloud\venv\lib\site-packages\flask_restful\__init__.py", line 269, in error_router
    return original_handler(e)
  File "C:\Users\*****\VectorCloud\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\*****\VectorCloud\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\*****\VectorCloud\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\*****\VectorCloud\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\*****\VectorCloud\vectorcloud\main\routes.py", line 217, in home
    settings_form=settings_form)
  File "C:\Users\*****\VectorCloud\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Users\*****\VectorCloud\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Users\*****\VectorCloud\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\*****\VectorCloud\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\*****\VectorCloud\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\*****\VectorCloud\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\*****\VectorCloud\vectorcloud\templates\home.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "C:\Users\*****\VectorCloud\vectorcloud\templates\layout.html", line 73, in top-level template code
    {% elif vector_status.battery_voltage > 3.85 %}
TypeError: '>' not supported between instances of 'NoneType' and 'float'`

I guess vector didn't send his battery status or something like that? He is in the same network and I tried it with chrome and Edge. If I can help you with any more infos, let me know. 
Thank you very much for your work. 
Dede

**Comment by Jasonthefirst** [comment]
Found my mistake. I had a wrong IP in 

> User/****/.anki_vector/sdk_config.ini

I tried the Anki SDK a few weeks ago and apparently the ip changed. But with the correct IP it is working. 
Thank you and consider this closed.
