### ISSUE TITLE
Post-install error `requires_behavior_control`

### ISSUE THREAD

**Issue by rsheyd** [rmountjoy92/VectorCloud#2]
I'm getting the following error when running VectorCloud right after installing using the steps on github page:
`TypeError: __init__() got an unexpected keyword argument 'requires_behavior_control'`

Traceback in terminal:
```
Traceback (most recent call last):
  File "/Users/roman.sheydvasser/dev/vector/env/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/roman.sheydvasser/dev/vector/env/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/roman.sheydvasser/dev/vector/env/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/roman.sheydvasser/dev/vector/env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/roman.sheydvasser/dev/vector/env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/roman.sheydvasser/dev/vector/env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/roman.sheydvasser/dev/vector/env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/roman.sheydvasser/dev/vector/env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/roman.sheydvasser/dev/vector/env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/roman.sheydvasser/dev/vector/env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/roman.sheydvasser/dev/vector/sdk/VectorCloud/vectorcloud/routes.py", line 107, in home
    get_stats()
  File "/Users/roman.sheydvasser/dev/vector/sdk/VectorCloud/vectorcloud/routes.py", line 25, in get_stats
    cache_animation_list=False) as robot:
TypeError: __init__() got an unexpected keyword argument 'requires_behavior_control'
```

**Comment by rmountjoy92** [comment]
Which version of the SDK do you have installed? requires_behavior_control was added in 0.5.0.

**Comment by rsheyd** [comment]
You were right, works great with sdk 0.5.0. Thanks! Can't wait to dive into this project, awesome work.
