### ISSUE TITLE
Error on initial setup

### ISSUE THREAD

**Issue by dorp7** [rmountjoy92/VectorCloud#21]
Got this error when trying to add my Vector:
I probably entered the wrong info for Vector, and I'm having trouble connecting to him with the phone app...

AttributeError

AttributeError: 'NoneType' object has no attribute 'serial'
Traceback (most recent call last)

    File "/home/jeff/vectorenv/vectorcloudapp/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__

    return self.wsgi_app(environ, start_response)

    File "/home/jeff/vectorenv/vectorcloudapp/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app

    response = self.handle_exception(e)

    File "/home/jeff/vectorenv/vectorcloudapp/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router

    return original_handler(e)

    File "/home/jeff/vectorenv/vectorcloudapp/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/home/jeff/vectorenv/vectorcloudapp/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise

    raise value

    File "/home/jeff/vectorenv/vectorcloudapp/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app

    response = self.full_dispatch_request()

    File "/home/jeff/vectorenv/vectorcloudapp/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/home/jeff/vectorenv/vectorcloudapp/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router

    return original_handler(e)

    File "/home/jeff/vectorenv/vectorcloudapp/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/home/jeff/vectorenv/vectorcloudapp/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise

    raise value

    File "/home/jeff/vectorenv/vectorcloudapp/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request

    rv = self.dispatch_request()

    File "/home/jeff/vectorenv/vectorcloudapp/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/home/jeff/vectorenv/vectorcloudapp/bin/VectorCloud/vectorcloud/user_system/routes.py", line 64, in welcome

    if form.vector_serial.data == top_vector.serial:

    AttributeError: 'NoneType' object has no attribute 'serial'

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

    dump() shows all variables in the frame
    dump(obj) dumps all that's known about the object

Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

**Comment by rmountjoy92** [comment]
Is there a config file in:
```
/home/jeff/.anki_vector/
```
?

**Comment by dorp7** [comment]
I don't know,  I out travelling and will check in a week.

**Comment by dorp7** [comment]
OK, just checked (I'm slow) and I found a file in that directory called Vector-E5V8-0040043c.cert
Is that a config file?

Also, I just got another error when trying to run this:
Installing collected packages: numpy, grpcio, aiogrpc, opencv-python, asn1crypto, pycparser, cffi, cryptography, itsdangerous, MarkupSafe, Jinja2, Werkzeug, click, flask, protobuf, googleapis-common-protos, anki-vector, SQLAlchemy, flask-sqlalchemy, bcrypt, flask-bcrypt, flask-login, WTForms, flask-wtf, Mako, python-editor, python-dateutil, alembic, flask-migrate, flask-script, aniso8601, pytz, flask-restful
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/lib/python3.7/site-packages/numpy-1.16.3.dist-info'                                  
Consider using the `--user` option or check the permissions.
